### ISSUE TITLE
Default URL causes ConnectionError

### ISSUE THREAD

**Issue by DistortedPumpkin** [joostsijm/supremacy1914_wrapper#5]
When I run the first demo example code (the one without a url (as i don't have a url)), it throws a ConnectionError due to it being an invalid URL

```python
Traceback (most recent call last):
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\eliya\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x037FF148>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xgs1.c.bytro.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x037FF148>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/eliya/PycharmProjects/supremacy/main.py", line 11, in <module>
    result = supremacy.players()
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\supremacy1914_wrapper\wrapper.py", line 59, in players
    return self._request(1)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\supremacy1914_wrapper\wrapper.py", line 83, in _request
    request = requests.post(self.url, headers=self.headers, json=params)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\eliya\PycharmProjects\supremacy\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='xgs1.c.bytro.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x037FF148>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by DistortedPumpkin** [comment]
^ btw the error is caused on the line `result = supremacy.players()`
